/**
 * School Seed Data - Top 50 US Universities
 *
 * Data sources:
 * - Basic info: College Scorecard API
 * - Additional context: Manual research for LLM notes
 *
 * Usage:
 *   npm run db:seed-schools
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Admissions cycle for deadline data (Fall 2026 enrollment = applying 2025-2026)
const ADMISSIONS_CYCLE = 2026;

interface SchoolSeed {
  name: string;
  city: string;
  state: string;
  country?: string;
  type: "private" | "public" | "liberal_arts";

  // Admission types
  hasEarlyDecision: boolean;
  hasEarlyDecisionII: boolean;
  hasEarlyAction: boolean;
  isRestrictiveEarlyAction: boolean;
  hasRollingAdmissions: boolean;
  admissionsNotes?: string;

  // Stats (from College Scorecard or latest available)
  acceptanceRate?: number; // 0.0 - 1.0
  satRange25?: number;
  satRange75?: number;
  actRange25?: number;
  actRange75?: number;
  undergradEnrollment?: number;

  // Costs
  tuition?: number;
  roomBoard?: number;
  avgFinancialAid?: number;

  // Links
  websiteUrl: string;

  // LLM Context (rich notes for advisor)
  notes?: string;

  // Metadata
  dataSource: string;
  dataStatus: string;

  // Deadlines for current cycle
  deadlines?: {
    deadlineEd?: Date;
    deadlineEd2?: Date;
    deadlineEa?: Date;
    deadlineRd?: Date;
    deadlinePriority?: Date;
    deadlineFinancialAid?: Date;
  };
}

// =============================================================================
// TOP 50 US UNIVERSITIES - Seed Data
// =============================================================================
// Note: Stats are approximate and should be verified. Deadlines are for 2025-2026 cycle.
// Data will be enriched via College Scorecard API and manual research.
// =============================================================================

const schools2026: SchoolSeed[] = [
  // =============================================================================
  // IVY LEAGUE (8 schools)
  // =============================================================================
  {
    name: "Harvard University",
    city: "Cambridge",
    state: "MA",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: true, // SCEA
    hasRollingAdmissions: false,
    acceptanceRate: 0.036,
    satRange25: 1510,
    satRange75: 1580,
    actRange25: 34,
    actRange75: 36,
    undergradEnrollment: 7500,
    tuition: 59076,
    roomBoard: 21130,
    avgFinancialAid: 59076,
    websiteUrl: "https://www.harvard.edu",
    notes: "Harvard is the oldest and most prestigious university in the US. Need-blind admissions with 100% demonstrated need met. No loans policy - all aid is grant-based. Famous for its liberal arts Core Curriculum. Strong in virtually every field. Boston/Cambridge location offers incredible opportunities. Alumni network is unparalleled. Testing reinstated for Class of 2030. SCEA means you cannot apply ED/EA elsewhere (except public schools). Acceptance rate ~3.6% with ~53,000 applicants. Known for diverse student body and residential house system.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-01"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Yale University",
    city: "New Haven",
    state: "CT",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: true, // SCEA
    hasRollingAdmissions: false,
    acceptanceRate: 0.045,
    satRange25: 1510,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 6500,
    tuition: 64700,
    roomBoard: 19680,
    avgFinancialAid: 62000,
    websiteUrl: "https://www.yale.edu",
    notes: "Yale is known for exceptional undergraduate focus despite being a research university. Residential college system creates tight-knit communities. Famous for drama, humanities, and political science but strong across the board. New Haven is a small city but improving. Need-blind with 100% need met. Test-flexible policy allows AP/IB scores in lieu of SAT/ACT. SCEA rate ~10.8% vs RD ~4.5%. Class of 2029 admitted 4.52% overall from 50,228 applicants. Secret societies and a cappella groups are part of the culture.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-02"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Princeton University",
    city: "Princeton",
    state: "NJ",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: true, // SCEA
    hasRollingAdmissions: false,
    acceptanceRate: 0.044,
    satRange25: 1510,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 5300,
    tuition: 59710,
    roomBoard: 20190,
    avgFinancialAid: 60000,
    websiteUrl: "https://www.princeton.edu",
    notes: "Princeton has no graduate schools in law, medicine, or business - all focus on undergrad. Famous for its eating clubs, beautiful campus, and undergraduate thesis requirement. No loans in financial aid packages. Very strong in engineering, public policy (Woodrow Wilson School), and STEM. Small town feel in New Jersey suburb. Class of 2029 admitted 4.4% from record 42,303 applicants. Known for rigorous academics and grade deflation (though easing). Honor code is taken very seriously.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-01"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Columbia University",
    city: "New York",
    state: "NY",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.039,
    satRange25: 1510,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 8600,
    tuition: 65524,
    roomBoard: 16800,
    avgFinancialAid: 58000,
    websiteUrl: "https://www.columbia.edu",
    notes: "Columbia's location in Manhattan is its defining feature - NYC is your campus. Famous Core Curriculum is rigorous humanities education. Strong in everything but particularly journalism, political science, and STEM. Urban campus in Morningside Heights. ED acceptance rate significantly higher than RD. Over 60,000 applicants, ~3.9% acceptance rate for Class of 2029. Need-blind with 100% need met. Campus life differs from rural Ivies - city integration is key. Engineering school (SEAS) admits separately.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-01"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "University of Pennsylvania",
    city: "Philadelphia",
    state: "PA",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.049,
    satRange25: 1510,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 10000,
    tuition: 63452,
    roomBoard: 18660,
    avgFinancialAid: 58000,
    websiteUrl: "https://www.upenn.edu",
    notes: "Penn is the most pre-professional Ivy with famous Wharton business school accessible to undergrads. Strong in nursing, engineering (SEAS), and arts/sciences. Philadelphia is affordable and livable with great food scene. Dual-degree programs popular (like M&T, Huntsman, Vagelos). Most selective year ever at 4.9% for Class of 2029. Testing required starting with Class of 2030. ED rate much higher - apply ED if Penn is your top choice. Known for collaborative culture despite intensity.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Brown University",
    city: "Providence",
    state: "RI",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.05,
    satRange25: 1500,
    satRange75: 1560,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 7000,
    tuition: 65656,
    roomBoard: 17974,
    avgFinancialAid: 57000,
    websiteUrl: "https://www.brown.edu",
    notes: "Brown's Open Curriculum is unique - no required courses, students design their education. Grade options include S/NC. Known for creative, independent thinkers. PLME (8-year BS/MD) is very competitive. Strong in liberal arts, sciences, and humanities. Providence is walkable and student-friendly. Testing reinstated. ED acceptance rate ~18% vs ~5% RD. Collaborative, non-competitive culture. Strong emphasis on undergraduate teaching. RISD cross-registration available.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Dartmouth College",
    city: "Hanover",
    state: "NH",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.06,
    satRange25: 1490,
    satRange75: 1560,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 4400,
    tuition: 63087,
    roomBoard: 19203,
    avgFinancialAid: 58000,
    websiteUrl: "https://home.dartmouth.edu",
    notes: "Dartmouth emphasizes undergraduate education in a small-town setting. D-Plan quarter system is unique - students take terms off for internships, study abroad. Famous for Tuck MBA and outdoor culture. Greek life is significant (~60% participation). Hanover is rural and isolated but beautiful. Testing reinstated. Strong alumni loyalty and network. Excellent study abroad programs. Engineering school is well-regarded. ED acceptance rate significantly higher than RD ~6%.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-02"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Cornell University",
    city: "Ithaca",
    state: "NY",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.07,
    satRange25: 1510,
    satRange75: 1560,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 15000,
    tuition: 63200,
    roomBoard: 17082,
    avgFinancialAid: 55000,
    websiteUrl: "https://www.cornell.edu",
    notes: "Cornell is the largest Ivy with 7 undergraduate colleges, each with different admission. Engineering, Hotel School, ILR, Agriculture, and Architecture are standouts. Beautiful but isolated gorge campus in Ithaca. Part private, part public (some NY state-funded colleges with lower tuition for NY residents). Testing reinstated. 72,519 applicants for Class of 2029 - largest pool ever. ED advantage is significant. Known for rigorous academics and some competitive culture. Research opportunities are abundant.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-02"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },

  // =============================================================================
  // TOP PRIVATE UNIVERSITIES (Non-Ivy)
  // =============================================================================
  {
    name: "Stanford University",
    city: "Stanford",
    state: "CA",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: true, // REA
    hasRollingAdmissions: false,
    acceptanceRate: 0.04,
    satRange25: 1510,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 8000,
    tuition: 62484,
    roomBoard: 20955,
    avgFinancialAid: 60000,
    websiteUrl: "https://www.stanford.edu",
    notes: "Stanford matches Harvard/Yale in prestige with Silicon Valley location as major differentiator. Known for entrepreneurship - many students start companies. Strong across engineering, CS, humanities, sciences. Beautiful campus, great weather. Need-blind with 100% need met, no loans. REA means no ED/EA elsewhere. ~4% acceptance rate. Quarter system. Strong athletics and school spirit. Innovation culture is pervasive. Close ties to tech industry for internships and jobs.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Massachusetts Institute of Technology",
    city: "Cambridge",
    state: "MA",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false, // Non-restrictive EA
    hasRollingAdmissions: false,
    acceptanceRate: 0.04,
    satRange25: 1530,
    satRange75: 1580,
    actRange25: 35,
    actRange75: 36,
    undergradEnrollment: 4600,
    tuition: 60156,
    roomBoard: 20424,
    avgFinancialAid: 55000,
    websiteUrl: "https://www.mit.edu",
    notes: "MIT is the world's premier STEM institution. Non-restrictive EA lets you apply elsewhere too - unique among top schools. Known for intense workload ('drinking from a firehose'), collaborative culture, and hands-on learning. Strong in engineering, CS, physics, math, and increasingly economics and biology. Boston/Cambridge location excellent. Need-blind with 100% need met. Maker culture and research opportunities abound. Pass/No Record first semester reduces stress. UROP program gives most students research experience.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "California Institute of Technology",
    city: "Pasadena",
    state: "CA",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: true, // REA
    hasRollingAdmissions: false,
    acceptanceRate: 0.03,
    satRange25: 1550,
    satRange75: 1580,
    actRange25: 35,
    actRange75: 36,
    undergradEnrollment: 1000,
    tuition: 62664,
    roomBoard: 20832,
    avgFinancialAid: 55000,
    websiteUrl: "https://www.caltech.edu",
    notes: "Caltech is tiny (~1000 undergrads) but mighty - extreme focus on STEM. Among the most selective and rigorous programs anywhere. Known for physics, engineering, chemistry, astronomy (JPL partnership). Very small, intense community. Pasadena location near LA. House system creates close bonds. Honor code allows take-home exams. Need-blind with 100% need met. 3:1 student-faculty ratio. Nearly everyone does research. Only for students who truly love science/engineering.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Duke University",
    city: "Durham",
    state: "NC",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.048,
    satRange25: 1510,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 6700,
    tuition: 63450,
    roomBoard: 19352,
    avgFinancialAid: 58000,
    websiteUrl: "https://www.duke.edu",
    notes: "Duke combines top academics with strong athletics and school spirit. Known for pre-med, public policy, engineering, and business. Beautiful Gothic campus in Durham, NC. Research Triangle location offers internships and jobs. Greek life present but not dominant. Basketball is religion here. ED acceptance rate much higher. 4.8% overall acceptance for Class of 2029. Need-aware for international students. Duke Engage program offers service opportunities. Strong alumni network in finance and consulting.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-04"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Northwestern University",
    city: "Evanston",
    state: "IL",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.07,
    satRange25: 1500,
    satRange75: 1560,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 8400,
    tuition: 64887,
    roomBoard: 19869,
    avgFinancialAid: 55000,
    websiteUrl: "https://www.northwestern.edu",
    notes: "Northwestern excels across journalism (Medill), engineering, theater, and music. Lake Michigan campus in Evanston is beautiful, close to Chicago. Quarter system. Known for pre-professional focus and internship opportunities. 7% acceptance for Class of 2029. ED is important - apply if Northwestern is top choice. Greek life is significant. School spirit for sports exists. Collaborative culture. Strong alumni network in media and business. Test-optional through 2025-26.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-03"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "University of Chicago",
    city: "Chicago",
    state: "IL",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.05,
    satRange25: 1510,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 7500,
    tuition: 65619,
    roomBoard: 19503,
    websiteUrl: "https://www.uchicago.edu",
    admissionsNotes: "Offers ED1, ED2, and EA. Known for quirky supplemental essays.",
    notes: "UChicago is famous for intellectual rigor and 'life of the mind' culture. Core Curriculum requires extensive humanities/sciences. Known for economics, physics, sociology, political science. Gothic campus in Hyde Park, Chicago. Unique essay prompts attract creative thinkers. 'Where fun goes to die' stereotype is outdated but academics are intense. Quarter system allows more courses. Strong in graduate/professional school placement. House system for residential life. Scavenger Hunt is legendary.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-06"),
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-06"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Johns Hopkins University",
    city: "Baltimore",
    state: "MD",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.06,
    satRange25: 1520,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 6000,
    tuition: 63340,
    roomBoard: 18760,
    avgFinancialAid: 52000,
    websiteUrl: "https://www.jhu.edu",
    notes: "Hopkins is the pre-med powerhouse - #1 hospital affiliation. Strong in BME, public health, international relations (SAIS), and neuroscience. Baltimore location is urban with safety concerns but improving. Research focus is intense. ~5.7% acceptance rate. Test-optional through Fall 2025 but requiring tests starting Fall 2026. ED/ED2 rates much higher. Competitive pre-med culture but collaborative elsewhere. Peabody Conservatory affiliation for music. D1 lacrosse is popular.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-02"),
      deadlineRd: new Date("2026-01-02"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Rice University",
    city: "Houston",
    state: "TX",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.078,
    satRange25: 1520,
    satRange75: 1570,
    actRange25: 34,
    actRange75: 36,
    undergradEnrollment: 4500,
    tuition: 58128,
    roomBoard: 16200,
    avgFinancialAid: 50000,
    websiteUrl: "https://www.rice.edu",
    notes: "Rice offers Ivy-caliber education at lower cost in Houston. Residential college system creates tight community. Known for engineering, architecture, sciences, and music. Beautiful campus with no gates. Houston offers internships in energy, medical center, NASA. Non-competitive culture. 7.8% acceptance rate. Small classes and close faculty relationships. Great value - tuition lower than peers. Strong pre-med advising. Rice/Baylor Med partnership for 8-year program.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-04"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Vanderbilt University",
    city: "Nashville",
    state: "TN",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.047,
    satRange25: 1500,
    satRange75: 1560,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 7100,
    tuition: 62250,
    roomBoard: 20418,
    avgFinancialAid: 55000,
    websiteUrl: "https://www.vanderbilt.edu",
    notes: "Vanderbilt has become extraordinarily selective - record low 4.7% for Class of 2029. Beautiful campus in Nashville, a booming city. Known for education, music business, pre-med, and engineering. Greek life is significant. Southern culture meets academic intensity. 100% need met policy. ED1 rate ~13% vs RD ~3.3%. Strong school spirit and social scene. Peabody College of Education is top-ranked. Music row access for music business. Balance of academics and fun.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-01"),
      deadlineRd: new Date("2026-01-01"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "University of Notre Dame",
    city: "Notre Dame",
    state: "IN",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: true, // REA
    hasRollingAdmissions: false,
    acceptanceRate: 0.12,
    satRange25: 1450,
    satRange75: 1540,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 8700,
    tuition: 62693,
    roomBoard: 17662,
    avgFinancialAid: 50000,
    websiteUrl: "https://www.nd.edu",
    notes: "Notre Dame is the premier Catholic university with intense school spirit and tradition. Football weekends are legendary. Known for business (Mendoza), engineering, architecture, and theology. South Bend is small and cold. Strong alumni network and loyalty. REA with January notification. ~12% acceptance rate. Living-learning communities instead of Greek life. Service orientation and community focus. Conservative Catholic identity may not suit everyone but creates cohesive culture.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-02"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Washington University in St. Louis",
    city: "St. Louis",
    state: "MO",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.11,
    satRange25: 1500,
    satRange75: 1560,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 8000,
    tuition: 61750,
    roomBoard: 20282,
    avgFinancialAid: 55000,
    websiteUrl: "https://wustl.edu",
    notes: "WashU has risen dramatically in rankings over recent decades. Beautiful campus in Clayton suburb of St. Louis. Known for pre-med, business (Olin), architecture, and social work. Strong research opportunities. ~11% acceptance rate. ED rates higher. Need-aware for aid. Very residential campus with great facilities. Collaborative, supportive culture. Barnes-Jewish Hospital affiliation for pre-med. Forest Park nearby offers recreation.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-04"),
      deadlineRd: new Date("2026-01-04"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Georgetown University",
    city: "Washington",
    state: "DC",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: true, // REA
    hasRollingAdmissions: false,
    acceptanceRate: 0.12,
    satRange25: 1440,
    satRange75: 1550,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 7900,
    tuition: 63620,
    roomBoard: 19476,
    avgFinancialAid: 48000,
    websiteUrl: "https://www.georgetown.edu",
    notes: "Georgetown is the premier school for international relations, politics, and diplomacy. DC location is its superpower - internships in government, think tanks, NGOs. Jesuit identity emphasizes service and ethics. School of Foreign Service is world-famous. McDonough business school strong. ~12% acceptance rate. REA with limited restrictions. Historic campus in Georgetown neighborhood. Strong alumni network in government. Basketball tradition. Cura personalis ('care for the whole person') philosophy.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-10"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Emory University",
    city: "Atlanta",
    state: "GA",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.145,
    satRange25: 1450,
    satRange75: 1530,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 7100,
    tuition: 59858,
    roomBoard: 17300,
    avgFinancialAid: 52000,
    websiteUrl: "https://www.emory.edu",
    notes: "Emory is known for exceptional pre-med (CDC headquarters nearby) and business (Goizueta). Atlanta location offers major city amenities and internships. Beautiful campus in Druid Hills. ~14.5% acceptance rate. Oxford College (2-year program) offers alternative entry. Strong research university with undergraduate focus. Need-aware but meets 100% demonstrated need. Greek life present. Southern hospitality culture. Coca-Cola money supports strong endowment.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-01"),
      deadlineRd: new Date("2026-01-01"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Carnegie Mellon University",
    city: "Pittsburgh",
    state: "PA",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.11,
    satRange25: 1510,
    satRange75: 1560,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 7300,
    tuition: 62260,
    roomBoard: 17360,
    avgFinancialAid: 48000,
    websiteUrl: "https://www.cmu.edu",
    notes: "CMU is a powerhouse for CS, engineering, robotics, and drama/design. Pittsburgh tech scene growing. Very intense workload - 'My heart is in the work' motto is real. Schools admit separately (SCS, Engineering, CFA, etc.) with different rates - CS extremely competitive. ~11.7% overall but varies by school. ED advantage exists. Interdisciplinary focus with unique majors. Silicon Valley recruiting is strong. Drama school is Ivy-equivalent for theater. Research opportunities abundant.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-03"),
      deadlineRd: new Date("2026-01-03"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "University of Southern California",
    city: "Los Angeles",
    state: "CA",
    type: "private",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.10,
    satRange25: 1450,
    satRange75: 1540,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 21000,
    tuition: 66640,
    roomBoard: 19098,
    avgFinancialAid: 45000,
    websiteUrl: "https://www.usc.edu",
    admissionsNotes: "No early application options. Single deadline for all applicants.",
    notes: "USC offers LA location, strong alumni network (Trojan Family), and top film school (SCA). No early admission options - single January deadline. ~10% acceptance rate. Known for communications, business (Marshall), engineering, and cinematic arts. Campus is urban but self-contained. Strong Greek life and school spirit (football). Entertainment industry connections unmatched. Expensive with less generous aid than Ivies. Very career-focused culture.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineRd: new Date("2026-01-15"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "New York University",
    city: "New York",
    state: "NY",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.08,
    satRange25: 1470,
    satRange75: 1550,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 28000,
    tuition: 60438,
    roomBoard: 21780,
    avgFinancialAid: 42000,
    websiteUrl: "https://www.nyu.edu",
    notes: "NYU is defined by NYC - no traditional campus, city is your campus. Highly selective now at 7.7% for Class of 2029. Known for Stern (business), Tisch (performing arts), and Tandon (engineering). Global network with campuses in Abu Dhabi and Shanghai. Expensive with historically less generous aid, but improving. ED rate higher - good strategy if NYU is top choice. Very diverse, cosmopolitan student body. Independent, urban experience.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-01"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Tufts University",
    city: "Medford",
    state: "MA",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.11,
    satRange25: 1480,
    satRange75: 1540,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 6500,
    tuition: 67844,
    roomBoard: 18150,
    avgFinancialAid: 52000,
    websiteUrl: "https://www.tufts.edu",
    notes: "Tufts is known for international relations (Fletcher School), engineering, and global perspective. Just outside Boston with easy T access. ~10.5-11.5% acceptance rate. Strong pre-med track. Civic engagement and active citizenship emphasized. Liberal, intellectual culture. Research opportunities good for school size. Test-optional. ED1/ED2 rates higher. Close-knit community despite urban-adjacent location. ExCollege offers quirky courses.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-04"),
      deadlineRd: new Date("2026-01-04"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Boston College",
    city: "Chestnut Hill",
    state: "MA",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.15,
    satRange25: 1430,
    satRange75: 1520,
    actRange25: 33,
    actRange75: 34,
    undergradEnrollment: 9500,
    tuition: 64176,
    roomBoard: 17058,
    avgFinancialAid: 48000,
    websiteUrl: "https://www.bc.edu",
    notes: "BC combines Jesuit education with strong athletics and school spirit. Gothic campus in Chestnut Hill, T access to Boston. Known for business (Carroll), nursing, education, and pre-law. ~15% acceptance rate. Strong Catholic identity and service orientation. Greek life prohibited but strong social scene. D1 football and basketball popular. Alumni network strong in Northeast business. Core curriculum emphasizes philosophy and theology.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-02"),
      deadlineRd: new Date("2026-01-02"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Boston University",
    city: "Boston",
    state: "MA",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.12,
    satRange25: 1420,
    satRange75: 1520,
    actRange25: 32,
    actRange75: 34,
    undergradEnrollment: 18000,
    tuition: 63798,
    roomBoard: 19270,
    avgFinancialAid: 44000,
    websiteUrl: "https://www.bu.edu",
    notes: "BU is a large research university integrated into Boston along Commonwealth Ave. Known for communications (COM), business (Questrom), engineering, and pre-med. ~11-13% acceptance rate (increasing selectivity). Urban campus with strong city integration. T runs through campus. Study abroad programs are excellent. Kilachand Honors College for top students. D1 hockey popular. Large, diverse student body. Strong alumni network in media.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-04"),
      deadlineRd: new Date("2026-01-04"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Case Western Reserve University",
    city: "Cleveland",
    state: "OH",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.30,
    satRange25: 1410,
    satRange75: 1520,
    actRange25: 32,
    actRange75: 34,
    undergradEnrollment: 5800,
    tuition: 59420,
    roomBoard: 17848,
    avgFinancialAid: 45000,
    websiteUrl: "https://www.case.edu",
    notes: "Case Western is strong in engineering, pre-med, and sciences with Cleveland Clinic/University Hospitals connections. University Circle location near museums and cultural institutions. ~30% acceptance rate - more accessible than other top schools. Strong merit scholarships available. Research opportunities abundant. Pre-professional focus. SAGES seminar program unique. Collaborative culture. CWRU/Cleveland Clinic BS/MD program highly competitive.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-15"),
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-15"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Northeastern University",
    city: "Boston",
    state: "MA",
    type: "private",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.06,
    satRange25: 1470,
    satRange75: 1540,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 15000,
    tuition: 62654,
    roomBoard: 19800,
    avgFinancialAid: 35000,
    websiteUrl: "https://www.northeastern.edu",
    admissionsNotes: "Known for co-op program. Offers ED, ED2, and EA.",
    notes: "Northeastern pioneered cooperative education - students alternate semesters between classes and paid work. Acceptance rate dropped to ~5-6% recently, making it extremely competitive. Known for engineering, business, health sciences. Boston location excellent. 5-year program standard due to co-ops. Strong career outcomes. Global network for international co-ops. Can graduate in 4 years with careful planning. Real-world experience distinguishes graduates.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-01"),
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-01"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },

  // =============================================================================
  // TOP PUBLIC UNIVERSITIES
  // =============================================================================
  {
    name: "University of California, Berkeley",
    city: "Berkeley",
    state: "CA",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.117,
    satRange25: 1330,
    satRange75: 1530,
    actRange25: 30,
    actRange75: 35,
    undergradEnrollment: 32000,
    tuition: 14312,
    roomBoard: 22014,
    avgFinancialAid: 24000,
    websiteUrl: "https://www.berkeley.edu",
    admissionsNotes: "UC system has single deadline (Nov 30). No early options. Test-free policy.",
    notes: "Berkeley is the #1 public university, rivaling Ivies academically. Test-free policy means no SAT/ACT in admissions. Strong in CS, engineering, business (Haas), sciences, and humanities. Bay Area location offers tech internships. Very large public school feel. ~11.7% acceptance rate but varies by major - CS as low as 4%. In-state tuition is affordable. Campus activism tradition. Diverse, politically active student body. Research opportunities abundant.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineRd: new Date("2025-11-30"),
      deadlineFinancialAid: new Date("2026-03-02"),
    },
  },
  {
    name: "University of California, Los Angeles",
    city: "Los Angeles",
    state: "CA",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.09,
    satRange25: 1310,
    satRange75: 1520,
    actRange25: 29,
    actRange75: 34,
    undergradEnrollment: 32000,
    tuition: 13804,
    roomBoard: 18516,
    avgFinancialAid: 22000,
    websiteUrl: "https://www.ucla.edu",
    admissionsNotes: "UC system has single deadline (Nov 30). No early options. Test-free policy.",
    notes: "UCLA is the most applied-to university in the US. ~9% acceptance rate - among most selective publics. Test-free policy. Known for film/TV, pre-med, engineering, and athletics. Westwood location near LA amenities. Beautiful campus. Strong school spirit. Some majors extremely competitive (nursing 1%, CS 3%). In-state tuition affordable. Large, diverse student body. Entertainment industry connections. Weather is a major draw.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineRd: new Date("2025-11-30"),
      deadlineFinancialAid: new Date("2026-03-02"),
    },
  },
  {
    name: "University of Michigan",
    city: "Ann Arbor",
    state: "MI",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.18,
    satRange25: 1400,
    satRange75: 1540,
    actRange25: 32,
    actRange75: 35,
    undergradEnrollment: 32000,
    tuition: 17228,
    roomBoard: 13684,
    avgFinancialAid: 19000,
    websiteUrl: "https://umich.edu",
    notes: "Michigan is a top public with exceptional school spirit (Go Blue!). Known for Ross Business School, engineering, LSA, and athletics. Ann Arbor is a great college town. ~18% overall acceptance but lower for competitive programs. EA is non-binding and recommended. OOS tuition is high. Strong research university with undergraduate focus. Football culture is massive. Alumni network excellent. Winter is cold.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-02-01"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "University of Virginia",
    city: "Charlottesville",
    state: "VA",
    type: "public",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.19,
    satRange25: 1400,
    satRange75: 1530,
    actRange25: 32,
    actRange75: 35,
    undergradEnrollment: 17000,
    tuition: 19584,
    roomBoard: 14540,
    avgFinancialAid: 22000,
    websiteUrl: "https://www.virginia.edu",
    admissionsNotes: "ED is binding. EA is available and non-restrictive.",
    notes: "UVA (founded by Jefferson) has beautiful campus and strong traditions. Known for Darden (MBA), McIntire (business), and pre-law. Charlottesville is charming college town. ~19% overall acceptance rate. ED and EA both available. Strong school spirit and Greek life. Honor system is serious. In-state advantage significant. Historical campus is UNESCO World Heritage Site. Southern culture present.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-03-01"),
    },
  },
  {
    name: "University of North Carolina at Chapel Hill",
    city: "Chapel Hill",
    state: "NC",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.17,
    satRange25: 1360,
    satRange75: 1510,
    actRange25: 30,
    actRange75: 34,
    undergradEnrollment: 20000,
    tuition: 9021,
    roomBoard: 13056,
    avgFinancialAid: 18000,
    websiteUrl: "https://www.unc.edu",
    notes: "UNC is the oldest public university with strong academics at public school price. Known for Kenan-Flagler Business School, journalism, pre-med, and basketball. Chapel Hill is quintessential college town. ~17% acceptance but heavily favors in-state (82% of students). EA is important. Carolina Covenant covers costs for low-income NC students. Strong Greek life and traditions. ACC basketball rivalry with Duke is intense.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-10-15"),
      deadlineRd: new Date("2026-01-15"),
      deadlineFinancialAid: new Date("2026-03-01"),
    },
  },
  {
    name: "Georgia Institute of Technology",
    city: "Atlanta",
    state: "GA",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.127,
    satRange25: 1420,
    satRange75: 1540,
    actRange25: 32,
    actRange75: 35,
    undergradEnrollment: 18000,
    tuition: 12682,
    roomBoard: 15164,
    avgFinancialAid: 16000,
    websiteUrl: "https://www.gatech.edu",
    notes: "Georgia Tech is a STEM powerhouse with engineering rivaling MIT/Stanford. Record-low 12.7% acceptance for Class of 2029 from 66,895 applicants. Known for CS, engineering, business (Scheller). Atlanta location offers internships. October 15 EA deadline is early. Intense academics but strong career outcomes. Yellow Jacket football has tradition. Affordable in-state, reasonable OOS. Co-op programs available.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-10-15"),
      deadlineRd: new Date("2026-01-04"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "University of Texas at Austin",
    city: "Austin",
    state: "TX",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.31,
    satRange25: 1230,
    satRange75: 1480,
    actRange25: 27,
    actRange75: 33,
    undergradEnrollment: 40000,
    tuition: 11698,
    roomBoard: 13620,
    avgFinancialAid: 14000,
    websiteUrl: "https://www.utexas.edu",
    admissionsNotes: "Priority/EA deadline Oct 15. Auto-admission for top 6% of Texas high school class.",
    notes: "UT Austin is a massive flagship with top programs in business (McCombs), engineering, CS, and communications. Austin is a great city. Auto-admit for top 6% Texas students takes most spots. OOS admission very competitive. New EA option (Oct 15 deadline). Hook 'em Horns school spirit. 80% of admits are Texans. Strong alumni network. Great value for in-state students. Competitive majors require specific applications.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-10-15"),
      deadlineRd: new Date("2025-12-01"),
      deadlineFinancialAid: new Date("2026-03-15"),
    },
  },
  {
    name: "University of Wisconsin-Madison",
    city: "Madison",
    state: "WI",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.49,
    satRange25: 1310,
    satRange75: 1470,
    actRange25: 28,
    actRange75: 33,
    undergradEnrollment: 35000,
    tuition: 11205,
    roomBoard: 13254,
    avgFinancialAid: 16000,
    websiteUrl: "https://www.wisc.edu",
    notes: "Wisconsin is a top public research university in a fun college town. Known for engineering, business, sciences, and dairy science (cheese!). Madison is a great city between two lakes. ~49% overall acceptance but competitive for popular majors. Strong Big Ten athletics and school spirit. Cold winters. Good value especially in-state. Research opportunities abundant. State Street and campus life are vibrant.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-02-01"),
      deadlineFinancialAid: new Date("2026-12-01"),
    },
  },
  {
    name: "University of Illinois Urbana-Champaign",
    city: "Champaign",
    state: "IL",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.45,
    satRange25: 1320,
    satRange75: 1510,
    actRange25: 28,
    actRange75: 34,
    undergradEnrollment: 35000,
    tuition: 17138,
    roomBoard: 13178,
    avgFinancialAid: 18000,
    websiteUrl: "https://illinois.edu",
    notes: "UIUC has top-ranked CS and engineering programs rivaling MIT/Stanford in those fields. Known for Grainger Engineering and Gies Business. College town in central Illinois. ~45% overall but CS/Engineering much more competitive. EA is recommended. Strong research university. Fighting Illini athletics. Large campus with lots of opportunities. Especially strong for tech recruiting. International student population is large.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-03-15"),
    },
  },
  {
    name: "University of Florida",
    city: "Gainesville",
    state: "FL",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.23,
    satRange25: 1360,
    satRange75: 1500,
    actRange25: 30,
    actRange75: 34,
    undergradEnrollment: 35000,
    tuition: 6380,
    roomBoard: 11620,
    avgFinancialAid: 12000,
    websiteUrl: "https://www.ufl.edu",
    notes: "UF is Florida's flagship with strong academics at amazing in-state value. Known for engineering, business (Warrington), health professions. Gainesville is a college town. ~23% acceptance rate. Gator Nation school spirit is intense. No early options - single November deadline. Bright Futures scholarship covers tuition for top FL students. SEC athletics. Warm weather. Growing selectivity.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineRd: new Date("2025-11-01"),
      deadlineFinancialAid: new Date("2025-12-15"),
    },
  },
  {
    name: "Ohio State University",
    city: "Columbus",
    state: "OH",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.53,
    satRange25: 1270,
    satRange75: 1450,
    actRange25: 27,
    actRange75: 32,
    undergradEnrollment: 46000,
    tuition: 12434,
    roomBoard: 14110,
    avgFinancialAid: 15000,
    websiteUrl: "https://www.osu.edu",
    notes: "Ohio State is massive with strong programs across the board. Known for Fisher Business School, engineering, and health sciences. Columbus is a major city. ~53% acceptance rate but honors programs competitive. EA is available. Football is religion (Ohio State-Michigan rivalry). Very large campus community. Good value especially in-state. Research opportunities abundant. Strong career services.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-02-01"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Penn State University",
    city: "University Park",
    state: "PA",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: true,
    acceptanceRate: 0.55,
    satRange25: 1210,
    satRange75: 1400,
    actRange25: 26,
    actRange75: 31,
    undergradEnrollment: 40000,
    tuition: 19836,
    roomBoard: 12854,
    avgFinancialAid: 12000,
    websiteUrl: "https://www.psu.edu",
    admissionsNotes: "Rolling admissions. Apply early for best consideration.",
    notes: "Penn State is a massive flagship with incredible school spirit. Known for Smeal Business, engineering, and athletics. Happy Valley (State College) is isolated college town. Rolling admissions - apply early. ~55% acceptance. Strong alumni network. Nittany Lions football is legendary. Multiple branch campuses feed into main campus. White Out games are famous. Large Greek life. We Are Penn State culture is strong.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlinePriority: new Date("2025-11-01"),
      deadlineRd: new Date("2025-11-30"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Purdue University",
    city: "West Lafayette",
    state: "IN",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: true,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.53,
    satRange25: 1210,
    satRange75: 1450,
    actRange25: 27,
    actRange75: 33,
    undergradEnrollment: 37000,
    tuition: 10002,
    roomBoard: 11854,
    avgFinancialAid: 14000,
    websiteUrl: "https://www.purdue.edu",
    notes: "Purdue is an engineering powerhouse with strong STEM programs. Known for Krannert Business, engineering (especially aerospace - astronaut makers!). West Lafayette is college town. ~53% overall but engineering very competitive. EA available. Tuition frozen for 12+ years - great value. Boilermaker Up! culture. Big Ten athletics. Research opportunities strong. Many NASA astronauts are alumni.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEa: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-15"),
      deadlineFinancialAid: new Date("2026-03-01"),
    },
  },
  {
    name: "University of Washington",
    city: "Seattle",
    state: "WA",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.48,
    satRange25: 1250,
    satRange75: 1460,
    actRange25: 28,
    actRange75: 33,
    undergradEnrollment: 36000,
    tuition: 12643,
    roomBoard: 15150,
    avgFinancialAid: 16000,
    websiteUrl: "https://www.washington.edu",
    notes: "UW is a top public with strong CS, engineering, and health sciences. Seattle location offers Amazon, Microsoft, Boeing internships. ~48% overall but CS/Engineering extremely competitive. No early options - single November deadline. Direct admission to some programs available. Beautiful campus. Strong research university. Tech industry connections excellent. Husky athletics. Cost-effective for WA residents.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineRd: new Date("2025-11-15"),
      deadlineFinancialAid: new Date("2026-02-28"),
    },
  },
  {
    name: "University of California, San Diego",
    city: "La Jolla",
    state: "CA",
    type: "public",
    hasEarlyDecision: false,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.24,
    satRange25: 1310,
    satRange75: 1510,
    actRange25: 29,
    actRange75: 34,
    undergradEnrollment: 33000,
    tuition: 14312,
    roomBoard: 16824,
    avgFinancialAid: 21000,
    websiteUrl: "https://ucsd.edu",
    admissionsNotes: "UC system has single deadline (Nov 30). No early options. Test-free policy.",
    notes: "UCSD is strong in STEM, especially bioengineering, CS, and sciences. La Jolla location near beach is beautiful. ~24% acceptance rate. Test-free policy. Known for research and pre-med track. College system creates smaller communities within large school. Less traditional campus feel. Biotech and pharma internship opportunities. Scripps Institute connection. Growing reputation. Beautiful weather.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineRd: new Date("2025-11-30"),
      deadlineFinancialAid: new Date("2026-03-02"),
    },
  },

  // =============================================================================
  // TOP LIBERAL ARTS COLLEGES
  // =============================================================================
  {
    name: "Williams College",
    city: "Williamstown",
    state: "MA",
    type: "liberal_arts",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.08,
    satRange25: 1500,
    satRange75: 1560,
    actRange25: 34,
    actRange75: 35,
    undergradEnrollment: 2100,
    tuition: 63770,
    roomBoard: 17600,
    avgFinancialAid: 60000,
    websiteUrl: "https://www.williams.edu",
    notes: "Williams is consistently ranked #1 liberal arts college. Remote Williamstown location (Berkshires) creates tight-knit community. Tutorial system (Oxford-style) is unique. Strong in all liberal arts disciplines. ~8% acceptance rate. ED acceptance rate ~27% is significant advantage. Need-blind with 100% need met. Beautiful campus. Excellent teaching focus. Division III athletics. Winter is cold and isolated. 88% of admits in top 10% of class.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-15"),
      deadlineRd: new Date("2026-01-08"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Amherst College",
    city: "Amherst",
    state: "MA",
    type: "liberal_arts",
    hasEarlyDecision: true,
    hasEarlyDecisionII: false,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.07,
    satRange25: 1500,
    satRange75: 1560,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 1900,
    tuition: 66750,
    roomBoard: 17600,
    avgFinancialAid: 62000,
    websiteUrl: "https://www.amherst.edu",
    notes: "Amherst has the most open curriculum of elite LACs - no requirements. Five College Consortium allows cross-registration at Smith, Mt. Holyoke, Hampshire, and UMass. ~7% acceptance rate. Test-optional through 2025-26. Known for producing Rhodes Scholars and academics. Need-blind with 100% need met. College town setting. Strong in all areas but particularly humanities and social sciences. Diverse student body.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineRd: new Date("2026-01-03"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Swarthmore College",
    city: "Swarthmore",
    state: "PA",
    type: "liberal_arts",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.07,
    satRange25: 1480,
    satRange75: 1550,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 1600,
    tuition: 62934,
    roomBoard: 18766,
    avgFinancialAid: 58000,
    websiteUrl: "https://www.swarthmore.edu",
    notes: "Swarthmore is the most academically rigorous LAC - known as intensely intellectual. Honors Program with seminars and external exams is unique. Strong engineering program (rare for LAC). ~7% acceptance rate. Test-optional through 2025-26. Quaker heritage emphasizes social responsibility. Near Philadelphia. Tri-Co (Bryn Mawr, Haverford) allows cross-registration. Need-blind with 100% need met. Known for producing PhDs and academics.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-15"),
      deadlineEd2: new Date("2026-01-04"),
      deadlineRd: new Date("2026-01-04"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Pomona College",
    city: "Claremont",
    state: "CA",
    type: "liberal_arts",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.07,
    satRange25: 1500,
    satRange75: 1550,
    actRange25: 33,
    actRange75: 35,
    undergradEnrollment: 1700,
    tuition: 60774,
    roomBoard: 19792,
    avgFinancialAid: 58000,
    websiteUrl: "https://www.pomona.edu",
    admissionsNotes: "Part of the Claremont Colleges consortium.",
    notes: "Pomona is the flagship of the Claremont Colleges - 5C consortium offers resources of a larger university. Southern California weather and location near LA. ~6-7% acceptance rate. Permanently test-optional. Strong in sciences, arts, and everything in between. Need-blind with 100% need met. Outdoor culture. Cross-registration across 5Cs (Pomona, CMC, Harvey Mudd, Scripps, Pitzer). Beautiful campus. Collaborative culture.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-15"),
      deadlineEd2: new Date("2026-01-08"),
      deadlineRd: new Date("2026-01-08"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Wellesley College",
    city: "Wellesley",
    state: "MA",
    type: "liberal_arts",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.13,
    satRange25: 1430,
    satRange75: 1530,
    actRange25: 32,
    actRange75: 34,
    undergradEnrollment: 2400,
    tuition: 65620,
    roomBoard: 19854,
    avgFinancialAid: 55000,
    websiteUrl: "https://www.wellesley.edu",
    admissionsNotes: "Women's college. Cross-registration with MIT.",
    notes: "Wellesley is the top women's college with strong academics and alumnae network. Cross-registration with MIT expands STEM options. Near Boston. ~13% acceptance rate. Beautiful lakeside campus. Known for producing leaders (Hillary Clinton, Madeleine Albright). Strong in economics, sciences, and all liberal arts. Need-blind with 100% need met. Supportive community focused on women's empowerment.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-08"),
      deadlineRd: new Date("2026-01-08"),
      deadlineFinancialAid: new Date("2026-02-01"),
    },
  },
  {
    name: "Bowdoin College",
    city: "Brunswick",
    state: "ME",
    type: "liberal_arts",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.09,
    satRange25: 1430,
    satRange75: 1530,
    actRange25: 32,
    actRange75: 34,
    undergradEnrollment: 1900,
    tuition: 64676,
    roomBoard: 17440,
    avgFinancialAid: 55000,
    websiteUrl: "https://www.bowdoin.edu",
    admissionsNotes: "Test-optional pioneer since 1969. No SAT/ACT required.",
    notes: "Bowdoin pioneered test-optional admissions in 1969. Beautiful coastal Maine location with access to outdoors. Known for excellent dining (best food of any college). ~9% acceptance rate. Strong in environmental sciences, government, and liberal arts. Need-blind with 100% need met. Tight-knit community. Division III athletics strong. Cold winters but stunning campus. Famous for producing Arctic explorers and outdoorspeople.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-15"),
      deadlineEd2: new Date("2026-01-05"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Middlebury College",
    city: "Middlebury",
    state: "VT",
    type: "liberal_arts",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.13,
    satRange25: 1410,
    satRange75: 1530,
    actRange25: 32,
    actRange75: 34,
    undergradEnrollment: 2800,
    tuition: 65250,
    roomBoard: 18650,
    avgFinancialAid: 52000,
    websiteUrl: "https://www.middlebury.edu",
    notes: "Middlebury is famous for language programs and Language Schools. Environmental studies pioneer. Vermont location is beautiful but isolated. ~13% acceptance rate. Strong in languages, international studies, and environmental science. J-term allows intensive study. Ski culture is significant. Need-aware but meets 100% need. Monterey Institute of International Studies is graduate school. Outdoor culture strong.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-15"),
      deadlineEd2: new Date("2026-01-08"),
      deadlineRd: new Date("2026-01-08"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
  {
    name: "Claremont McKenna College",
    city: "Claremont",
    state: "CA",
    type: "liberal_arts",
    hasEarlyDecision: true,
    hasEarlyDecisionII: true,
    hasEarlyAction: false,
    isRestrictiveEarlyAction: false,
    hasRollingAdmissions: false,
    acceptanceRate: 0.10,
    satRange25: 1450,
    satRange75: 1530,
    actRange25: 32,
    actRange75: 35,
    undergradEnrollment: 1400,
    tuition: 63885,
    roomBoard: 19750,
    avgFinancialAid: 52000,
    websiteUrl: "https://www.cmc.edu",
    admissionsNotes: "Part of the Claremont Colleges consortium. Strong in economics and government.",
    notes: "CMC is the most pre-professional of elite LACs, focused on economics, government, and leadership. Part of 5C consortium. Strong finance and consulting placement. ~10% acceptance rate. Southern California weather and location. Washington DC internship program popular. Research institutes (like Rose Institute) offer opportunities. Need-aware but generous aid. More conservative than typical LAC. Known for producing business leaders.",
    dataSource: "research_2024",
    dataStatus: "verified",
    deadlines: {
      deadlineEd: new Date("2025-11-01"),
      deadlineEd2: new Date("2026-01-05"),
      deadlineRd: new Date("2026-01-05"),
      deadlineFinancialAid: new Date("2026-02-15"),
    },
  },
];

async function seedSchools() {
  console.log("Seeding schools...");

  for (const schoolData of schools2026) {
    const { deadlines, ...school } = schoolData;

    const existing = await prisma.school.findUnique({
      where: { name: school.name },
    });

    if (existing) {
      console.log(`  Updating: ${school.name}`);

      // Update the school
      await prisma.school.update({
        where: { id: existing.id },
        data: {
          ...school,
          lastUpdated: new Date(),
        },
      });

      // Update or create deadline year if provided
      if (deadlines) {
        await prisma.schoolDeadlineYear.upsert({
          where: {
            schoolId_admissionsCycle: {
              schoolId: existing.id,
              admissionsCycle: ADMISSIONS_CYCLE,
            },
          },
          update: {
            ...deadlines,
            dataSource: "manual",
          },
          create: {
            schoolId: existing.id,
            admissionsCycle: ADMISSIONS_CYCLE,
            ...deadlines,
            dataSource: "manual",
          },
        });
      }
    } else {
      console.log(`  Creating: ${school.name}`);

      // Create school with deadlines
      const newSchool = await prisma.school.create({
        data: school,
      });

      // Create deadline year if provided
      if (deadlines) {
        await prisma.schoolDeadlineYear.create({
          data: {
            schoolId: newSchool.id,
            admissionsCycle: ADMISSIONS_CYCLE,
            ...deadlines,
            dataSource: "manual",
          },
        });
      }
    }
  }

  console.log(`Seeded ${schools2026.length} schools`);
}

async function main() {
  try {
    await seedSchools();
    console.log("\nSchool seeding complete!");
  } catch (error) {
    console.error("Error seeding schools:", error);
    throw error;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
