"use client";

import React, { useEffect, useState } from "react";
import {
  Calendar,
  Clock,
  School,
  Building2,
  Target,
  FileText,
  Check,
  AlertTriangle,
  ChevronDown,
  ChevronRight,
  Filter,
  Flag,
  Bell,
} from "lucide-react";
import { cn } from "@/lib/utils";

// =============================================================================
// TYPES
// =============================================================================

interface TimelineItem {
  id: string;
  type: "task" | "goal";
  taskType: "milestone" | "action";  // milestone = informational, action = completable
  title: string;
  description: string | null;
  dueDate: string | null;
  status: string;
  priority: string | null;
  sourceType: "school" | "program" | "test" | "manual";
  deadlineType: string | null;
  isHardDeadline: boolean;
  isAutoGenerated: boolean;
  goal: { id: string; title: string; category: string } | null;
  school: { id: string; name: string; shortName: string | null } | null;
  program: { id: string; name: string; shortName: string | null } | null;
  parentTask: { id: string; title: string } | null;
}

interface GroupedTimeline {
  overdue: TimelineItem[];
  today: TimelineItem[];
  thisWeek: TimelineItem[];
  nextWeek: TimelineItem[];
  thisMonth: TimelineItem[];
  later: TimelineItem[];
}

interface TimelineResponse {
  items: TimelineItem[];
  grouped: GroupedTimeline;
  total: number;
  filter: string;
  range: string;
}

// =============================================================================
// MAIN COMPONENT
// =============================================================================

export function TimelineView() {
  const [data, setData] = useState<TimelineResponse | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<"all" | "schools" | "programs" | "goals" | "tests">("all");
  const [showCompleted, setShowCompleted] = useState(false);
  const [expandedGroups, setExpandedGroups] = useState<Record<string, boolean>>({
    overdue: true,
    today: true,
    thisWeek: true,
    nextWeek: true,
    thisMonth: true,
    later: true,
  });

  // Fetch timeline data
  useEffect(() => {
    async function fetchTimeline() {
      setIsLoading(true);
      try {
        const params = new URLSearchParams({
          filter,
          range: "all",
          completed: showCompleted.toString(),
        });
        const res = await fetch(`/api/plan/timeline?${params}`);
        if (!res.ok) throw new Error("Failed to fetch timeline");
        const data = await res.json();
        setData(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : "An error occurred");
      } finally {
        setIsLoading(false);
      }
    }
    fetchTimeline();
  }, [filter, showCompleted]);

  const toggleGroup = (group: string) => {
    setExpandedGroups(prev => ({ ...prev, [group]: !prev[group] }));
  };

  const toggleTask = async (itemId: string, currentStatus: string) => {
    // Optimistic update
    if (!data) return;

    const newStatus = currentStatus === "completed" ? "pending" : "completed";
    setData(prev => {
      if (!prev) return prev;
      const updateItems = (items: TimelineItem[]) =>
        items.map(item =>
          item.id === itemId ? { ...item, status: newStatus } : item
        );

      return {
        ...prev,
        items: updateItems(prev.items),
        grouped: {
          overdue: updateItems(prev.grouped.overdue),
          today: updateItems(prev.grouped.today),
          thisWeek: updateItems(prev.grouped.thisWeek),
          nextWeek: updateItems(prev.grouped.nextWeek),
          thisMonth: updateItems(prev.grouped.thisMonth),
          later: updateItems(prev.grouped.later),
        },
      };
    });

    // Sync with server
    try {
      await fetch(`/api/plan/tasks/${itemId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: newStatus }),
      });
    } catch (err) {
      console.error("Failed to update task:", err);
      // Rollback on error
      setData(prev => {
        if (!prev) return prev;
        const updateItems = (items: TimelineItem[]) =>
          items.map(item =>
            item.id === itemId ? { ...item, status: currentStatus } : item
          );

        return {
          ...prev,
          items: updateItems(prev.items),
          grouped: {
            overdue: updateItems(prev.grouped.overdue),
            today: updateItems(prev.grouped.today),
            thisWeek: updateItems(prev.grouped.thisWeek),
            nextWeek: updateItems(prev.grouped.nextWeek),
            thisMonth: updateItems(prev.grouped.thisMonth),
            later: updateItems(prev.grouped.later),
          },
        };
      });
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="w-8 h-8 border-2 border-accent-primary border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12">
        <p className="text-red-500">{error}</p>
      </div>
    );
  }

  if (!data || data.total === 0) {
    return (
      <div className="text-center py-12">
        <div className="w-16 h-16 bg-accent-surface rounded-2xl flex items-center justify-center mx-auto mb-4">
          <Calendar className="w-8 h-8 text-accent-primary" />
        </div>
        <h2 className="font-display font-bold text-xl mb-2">No upcoming deadlines</h2>
        <p className="text-text-muted max-w-md mx-auto">
          When you add schools or programs to your list, their deadlines will appear here.
        </p>
      </div>
    );
  }

  const groupLabels: Record<string, { label: string; icon: React.ReactNode }> = {
    overdue: { label: "Overdue", icon: <AlertTriangle className="w-4 h-4 text-red-500" /> },
    today: { label: "Today", icon: <Clock className="w-4 h-4 text-amber-500" /> },
    thisWeek: { label: "This Week", icon: <Calendar className="w-4 h-4 text-accent-primary" /> },
    nextWeek: { label: "Next Week", icon: <Calendar className="w-4 h-4 text-text-muted" /> },
    thisMonth: { label: "This Month", icon: <Calendar className="w-4 h-4 text-text-muted" /> },
    later: { label: "Later", icon: <Calendar className="w-4 h-4 text-text-light" /> },
  };

  return (
    <div className="space-y-6">
      {/* Filters */}
      <div className="flex items-center gap-2 flex-wrap">
        <Filter className="w-4 h-4 text-text-muted" />
        <FilterButton
          active={filter === "all"}
          onClick={() => setFilter("all")}
          label="All"
        />
        <FilterButton
          active={filter === "schools"}
          onClick={() => setFilter("schools")}
          icon={<School className="w-3 h-3" />}
          label="Schools"
        />
        <FilterButton
          active={filter === "programs"}
          onClick={() => setFilter("programs")}
          icon={<Building2 className="w-3 h-3" />}
          label="Programs"
        />
        <FilterButton
          active={filter === "goals"}
          onClick={() => setFilter("goals")}
          icon={<Target className="w-3 h-3" />}
          label="Goals"
        />
        <FilterButton
          active={filter === "tests"}
          onClick={() => setFilter("tests")}
          icon={<FileText className="w-3 h-3" />}
          label="Tests"
        />
        <div className="flex-1" />
        <label className="flex items-center gap-2 text-sm text-text-muted cursor-pointer">
          <input
            type="checkbox"
            checked={showCompleted}
            onChange={(e) => setShowCompleted(e.target.checked)}
            className="rounded border-border-medium"
          />
          Show completed
        </label>
      </div>

      {/* Timeline Groups */}
      <div className="space-y-4">
        {(Object.keys(groupLabels) as Array<keyof GroupedTimeline>).map((groupKey) => {
          const items = data.grouped[groupKey];
          if (items.length === 0) return null;

          const { label, icon } = groupLabels[groupKey];
          const isExpanded = expandedGroups[groupKey];

          return (
            <div key={groupKey} className="bg-white border border-border-subtle rounded-xl overflow-hidden">
              {/* Group Header */}
              <button
                onClick={() => toggleGroup(groupKey)}
                className={cn(
                  "w-full flex items-center gap-3 px-4 py-3 text-left transition-colors",
                  groupKey === "overdue" && "bg-red-50",
                  groupKey === "today" && "bg-amber-50"
                )}
              >
                {isExpanded ? (
                  <ChevronDown className="w-4 h-4 text-text-muted" />
                ) : (
                  <ChevronRight className="w-4 h-4 text-text-muted" />
                )}
                {icon}
                <span className={cn(
                  "font-display font-bold",
                  groupKey === "overdue" && "text-red-700",
                  groupKey === "today" && "text-amber-700"
                )}>
                  {label}
                </span>
                <span className="text-xs text-text-muted">({items.length})</span>
              </button>

              {/* Group Items */}
              {isExpanded && (
                <div className="divide-y divide-border-subtle">
                  {items.map((item) => (
                    <TimelineItemRow
                      key={item.id}
                      item={item}
                      onToggle={() => toggleTask(item.id, item.status)}
                      isOverdue={groupKey === "overdue"}
                    />
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// =============================================================================
// SUB-COMPONENTS
// =============================================================================

function FilterButton({
  active,
  onClick,
  icon,
  label,
}: {
  active: boolean;
  onClick: () => void;
  icon?: React.ReactNode;
  label: string;
}) {
  return (
    <button
      onClick={onClick}
      className={cn(
        "flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium transition-colors",
        active
          ? "bg-accent-primary text-white"
          : "bg-bg-sidebar text-text-muted hover:bg-border-subtle"
      )}
    >
      {icon}
      {label}
    </button>
  );
}

function TimelineItemRow({
  item,
  onToggle,
  isOverdue,
}: {
  item: TimelineItem;
  onToggle: () => void;
  isOverdue: boolean;
}) {
  const isCompleted = item.status === "completed";
  const isMilestone = item.taskType === "milestone";

  const getSourceIcon = () => {
    switch (item.sourceType) {
      case "school":
        return <School className="w-4 h-4" />;
      case "program":
        return <Building2 className="w-4 h-4" />;
      case "test":
        return <FileText className="w-4 h-4" />;
      default:
        return <Target className="w-4 h-4" />;
    }
  };

  const getSourceLabel = () => {
    if (item.school) return item.school.shortName || item.school.name;
    if (item.program) return item.program.shortName || item.program.name;
    if (item.goal) return item.goal.title;
    return null;
  };

  const formatDate = (dateStr: string | null) => {
    if (!dateStr) return null;
    const date = new Date(dateStr);
    return date.toLocaleDateString("en-US", {
      weekday: "short",
      month: "short",
      day: "numeric",
    });
  };

  // Get milestone icon based on deadline type
  const getMilestoneIcon = () => {
    if (item.deadlineType?.includes("notification")) {
      return <Bell className="w-3 h-3 text-blue-500" />;
    }
    if (item.deadlineType?.includes("program_start") || item.deadlineType?.includes("program_end")) {
      return <Calendar className="w-3 h-3 text-green-500" />;
    }
    return <Flag className="w-3 h-3 text-amber-500" />;
  };

  return (
    <div
      className={cn(
        "flex items-center gap-4 px-4 py-3 hover:bg-bg-sidebar/50 transition-colors",
        isCompleted && "opacity-60",
        isMilestone && "bg-gradient-to-r from-blue-50/50 to-transparent"
      )}
    >
      {/* Icon - Checkbox for actions, Flag/Calendar for milestones */}
      {isMilestone ? (
        // Milestone indicator (no checkbox)
        <div className="w-5 h-5 rounded-full bg-blue-100 flex items-center justify-center shrink-0">
          {getMilestoneIcon()}
        </div>
      ) : item.type === "task" ? (
        // Action checkbox
        <button
          onClick={onToggle}
          className={cn(
            "w-5 h-5 rounded border-2 flex items-center justify-center transition-colors shrink-0",
            isCompleted
              ? "bg-accent-primary border-accent-primary text-white"
              : "border-border-medium hover:border-accent-primary"
          )}
        >
          {isCompleted && <Check className="w-3 h-3" />}
        </button>
      ) : (
        // Goal indicator
        <div className="w-5 h-5 rounded-full bg-accent-surface flex items-center justify-center shrink-0">
          <Target className="w-3 h-3 text-accent-primary" />
        </div>
      )}

      {/* Content */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <span
            className={cn(
              "font-medium truncate",
              isCompleted && "line-through text-text-muted",
              isOverdue && !isCompleted && !isMilestone && "text-red-700",
              isMilestone && "text-blue-700"
            )}
          >
            {item.title}
          </span>
          {isMilestone && (
            <span className="px-1.5 py-0.5 bg-blue-100 text-blue-700 text-xs rounded font-medium">
              Info
            </span>
          )}
          {!isMilestone && item.isHardDeadline && !isCompleted && (
            <span className="px-1.5 py-0.5 bg-red-100 text-red-700 text-xs rounded font-medium">
              Hard
            </span>
          )}
        </div>

        {/* Source Badge */}
        {getSourceLabel() && (
          <div className="flex items-center gap-1.5 mt-1 text-xs text-text-muted">
            {getSourceIcon()}
            <span>{getSourceLabel()}</span>
          </div>
        )}
      </div>

      {/* Date */}
      <div className="text-right shrink-0">
        <span
          className={cn(
            "text-sm",
            isOverdue && !isCompleted ? "text-red-600 font-medium" : "text-text-muted"
          )}
        >
          {formatDate(item.dueDate)}
        </span>
      </div>
    </div>
  );
}
